[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pymongo>=3.12.1"
]
build-backend = "setuptools.build_meta"
[tool.pytest.ini_options]
pythonpath = [
  ""
]
[tool.ruff]
# Allow imports relative to the "src" and "test" directories.
src = ["src", "test"]
line-length = 100